component_depth: 1
languages:
- java
exclude:
- ./lib/.*
- ./proposals/.*
- ./proposals/TLP/.*
- ./proposals/imap/.*
- ./proposals/imap/conf/.*
- ./proposals/imap/java/.*
- ./proposals/imap/java/lib/.*
- ./proposals/imap/java/org/.*
- ./proposals/imap/java/org/apache/.*
- ./proposals/imap/java/org/apache/james/.*
- ./proposals/imap/java/org/apache/james/imapserver/.*
- ./proposals/imap/java/org/apache/james/imapserver/commands/.*
- ./proposals/imap/java/org/apache/james/util/.*
- ./proposals/imap/test/.*
- ./proposals/imap/test/lib/.*
- ./proposals/imap/test/org/.*
- ./proposals/imap/test/org/apache/.*
- ./proposals/imap/test/org/apache/james/.*
- ./proposals/imap/test/org/apache/james/imapserver/.*
- ./proposals/imap/test/org/apache/james/imapserver/commands/.*
- ./proposals/imap/test/org/apache/james/remotemanager/.*
- ./proposals/imap/test/org/apache/james/smtpserver/.*
- ./proposals/imap/test/org/apache/james/test/.*
- ./proposals/imap/www/.*
- ./proposals/imap/xdocs/.*
- ./proposals/imap2/.*
- ./proposals/imap2/conf/.*
- ./proposals/imap2/java/.*
- ./proposals/imap2/java/lib/.*
- ./proposals/imap2/java/org/.*
- ./proposals/imap2/java/org/apache/.*
- ./proposals/imap2/java/org/apache/james/.*
- ./proposals/imap2/java/org/apache/james/imapserver/.*
- ./proposals/imap2/java/org/apache/james/imapserver/commands/.*
- ./proposals/imap2/java/org/apache/james/imapserver/store/.*
- ./proposals/imap2/java/org/apache/james/util/.*
- ./proposals/imap2/test/.*
- ./proposals/imap2/test/lib/.*
- ./proposals/imap2/test/org/.*
- ./proposals/imap2/test/org/apache/.*
- ./proposals/imap2/test/org/apache/james/.*
- ./proposals/imap2/test/org/apache/james/imapserver/.*
- ./proposals/imap2/test/org/apache/james/remotemanager/.*
- ./proposals/imap2/test/org/apache/james/smtpserver/.*
- ./proposals/imap2/test/org/apache/james/test/.*
- ./proposals/rmi-remotemanager/.*
- ./proposals/rmi-remotemanager/conf/.*
- ./proposals/rmi-remotemanager/java/.*
- ./proposals/rmi-remotemanager/java/lib/.*
- ./proposals/rmi-remotemanager/java/org/.*
- ./proposals/rmi-remotemanager/java/org/apache/.*
- ./proposals/rmi-remotemanager/java/org/apache/james/.*
- ./proposals/rmi-remotemanager/java/org/apache/james/client/.*
- ./proposals/rmi-remotemanager/java/org/apache/james/core/.*
- ./proposals/rmi-remotemanager/java/org/apache/james/remotemanager/.*
- ./proposals/rmi-remotemanager/java/org/apache/james/services/.*
- ./proposals/sasl/.*
- ./tools/.*
- ./tools/bin/.*
- ./tools/etc/.*
- ./tools/lib/.*
- ./www/.*
- ./www/rfclist/.*
- ./www/rfclist/basic/.*
- ./www/rfclist/imap4/.*
- ./www/rfclist/ldap/.*
- ./www/rfclist/nntp/.*
- ./www/rfclist/pop3/.*
- ./www/rfclist/smtp/.*
